/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_soling_hellojni_MainActivity */

#ifndef _Included_com_soling_hellojni_MainActivity
#define _Included_com_soling_hellojni_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_soling_hellojni_MainActivity
 * Method:    getHelloJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_soling_hellojni_MainActivity_getHelloJniString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
